# -*- coding: utf-8 -*-
"""employee-salary-calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjPzEc7QxCnuOGhC3rDOV3yQDql6TtvP
"""

def calculate_salary(basic_salary, overtime_hours):
  normal_workinghours = 160
  overtime_pay = overtime_hours * 500

  if overtime_hours > 20:
    bonus = 5000
  else:
    bonus = 0

  final_salary = basic_salary + overtime_pay + bonus

  print("Working hours:", normal_workinghours)
  print("Basic salary:", basic_salary)
  print("Over time hours:", overtime_hours)
  print("Over time pay:", overtime_pay)
  print("Bonus:", bonus)
  print("Final salary:", final_salary)


basic_salary = int(input("Enter basic salary: "))
overtime_hours = int(input("Enter overtime hours: "))
calculate_salary(basic_salary, overtime_hours)