# -*- coding: utf-8 -*-
"""Employee-perf&bonus-system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3UROoMes9ZCA9ofRNLgsO97lNFEB8UU
"""

def calculate_bonus(name, salary, projects, performance):

    if performance >= 90:
        level = "Excellent"
    elif performance >= 80:
        level = "Very Good"
    elif performance >= 70:
        level = "Good"
    else:
        level = "Needs Improvement"

    if level == "Excellent" and projects >= 3:
        bonus_percent = 20
    elif level == "Very Good" and projects >= 3:
        bonus_percent = 15
    elif level == "Good" and projects >= 2:
        bonus_percent = 10
    else:
        bonus_percent = 0

    bonus = salary * bonus_percent / 100
    final_salary = salary + bonus

    print("Employee:", name)
    print("Performance:", level)
    print("Projects:", projects)
    print("Bonus:", int(bonus))
    print("Final Salary:", int(final_salary))


calculate_bonus("Ali", 80000, 4, 92)