# -*- coding: utf-8 -*-
"""hotel room booking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnGolm7tJjlwfywcoE_xAuqJrIscFyaq
"""

def calculate_hotel_bill(room_type, nights, breakfast=False):

    if room_type == "Standard":
        price = 5000
    elif room_type == "Deluxe":
        price = 8000
    elif room_type == "Suite":
        price = 15000
    else:
        return "Invalid room type"

    # Breakfast
    if breakfast:
        price += 1000

    total = price * nights

    # Discount
    if nights >= 7:
        discount = 15
    elif nights >= 3:
        discount = 10
    else:
        discount = 0

    discount_amount = total * discount / 100
    final_bill = total - discount_amount

    return final_bill


# Example
print(calculate_hotel_bill("Deluxe", 5))
print(calculate_hotel_bill("Suite", 7, True))