# -*- coding: utf-8 -*-
"""mobile-package-billing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExrDZN42t7_jo-ix6pYftIKr9WzWMlxx
"""

def calculate_mobile_bill(package, extra_gb):

    if package == "Basic":
        price = 1000
        free_gb = 0

    elif package == "Standard":
        price = 1500
        free_gb = 2

    elif package == "Premium":
        price = 2500
        free_gb = 5

    else:
        return "Invalid package"

    # Charged GB
    if extra_gb > free_gb:
        charged_gb = extra_gb - free_gb
    else:
        charged_gb = 0

    # Extra charges
    extra_charges = charged_gb * 100

    # Final bill
    final_bill = price + extra_charges

    return final_bill


print(calculate_mobile_bill("Standard", 5))